import org.gradle.cli.CommandLineOption

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

tasks.register("printGradleDistLibraryPath") {
    doFirst {
        println("Gradle user home: ${gradle.gradleUserHomeDir}")
        // take any class from dist libraries
        println("org.gradle.cli.CommandLineOption is coming from ${CommandLineOption::class.java.getResource("/org/gradle/cli/CommandLineOption.class")}")
    }
}